### ISSUE TITLE
CPU Platform for shasta_inmem_t Task

### ISSUE THREAD

**Issue by Xinyu-Sun** [nanoporegenomics/variant_calling_wf#13]
Hello,

I have a question regarding line 124 in the `shasta_inmem_t task` within the `shasta.wdl` file:

https://github.com/nanoporegenomics/napu_wf/blob/33ac672fdbcd6ba144b360c9aacfdde4ee68b121/wdl/tasks/shasta.wdl#L124

Is it necessary to specify the CPU platform as "AMD Rome"? I am planning to run the pipeline on AWS. If using AMD Rome is required, could anyone suggest suitable instance types?

Thank you,
Xinyu

**Comment by mikolmogorov** [comment]
Hi Xinyu,

It does not have to be `AMD Rome` - you can select any CPU platform, as long as it can provide the necessary CPU and RAM resources.

Misha

**Comment by Xinyu-Sun** [comment]
Thank you, Misha!
