### ISSUE TITLE
Multiple input bams

### ISSUE THREAD

**Issue by wharvey31** [nanoporegenomics/variant_calling_wf#3]
Hello,

I was wondering if you had a procedure to integrate multiple input bams? Do I add them as a list of strings to the json file or is there currently not functionality for this?

Thanks so much for your efforts to this point!

**Comment by mikolmogorov** [comment]
Hi @wharvey31 

Sorry for the late response! Currently the pipeline only accepts a single bam. A workaround would be to merge all input bams into a single file. We are planning to add the support of multiple bams in the upcoming updates!

Misha

**Comment by mikolmogorov** [comment]
I think @meredith705 have added support for multiple bams input, has it been merged with the main r9/r10 branches?

**Comment by meredith705** [comment]
Hi @wharvey31, 

This enhancement is now available in the `R9_muliple_inputs` and `R10_multiple_inputs` branches. 

These will be merged into just `R9` and `R10` branches very soon. 

Thank you for your comment!
Melissa M
