### ISSUE TITLE
Different sample names in hapdiff_unphased.vcf.gz_size_filtered.vcf

### ISSUE THREAD

**Issue by saraheger** [nanoporegenomics/variant_calling_wf#7]
Hi, I tried to run the Quick demo, but got this error. Please advise. Thanks

[2023-08-16 17:30:07,27] [info] WorkflowManagerActor: Workflow b723869b-5486-4002-8528-d607428b4ad7 failed (during ExecutingWorkflowState): Job runMarginPhase.combineVcfs:NA:1 exited with return code 255 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /home/eger/projects/CARD_LRS/card_pipeline_small_test/cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/execution/stderr.
 [First 3000 bytes]:+ SV_FILTERED=/cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/1565723404/hapdiff_unphased.vcf.gz_size_filtered.vcf
+ SMALL_FILTERED=/cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/-490589013/PMDV_FINAL.phased.vcf.gz_size_filtered.vcf
+ zcat -f /cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/1565723404/hapdiff_unphased.vcf.gz
+ python3 /opt/vcf_filter_size.py greater 25
+ bgzip
+ tabix -p vcf /cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/1565723404/hapdiff_unphased.vcf.gz_size_filtered.vcf
+ zcat -f /cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/-490589013/PMDV_FINAL.phased.vcf.gz
+ python3 /opt/vcf_filter_size.py less 25
+ bgzip
+ tabix -p vcf /cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/-490589013/PMDV_FINAL.phased.vcf.gz_size_filtered.vcf
+ bcftools concat -a /cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/-490589013/PMDV_FINAL.phased.vcf.gz_size_filtered.vcf /cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/1565723404/hapdiff_unphased.vcf.gz_size_filtered.vcf -o hg002.merged_small_svs.vcf
Different sample names in /cromwell-executions/cardEndToEndVcfMethyl/b723869b-5486-4002-8528-d607428b4ad7/call-margin_phase/runMarginPhase/a4543c92-3556-48de-a9a1-06a4f7fc497f/call-combineVcfs/inputs/1565723404/hapdiff_unphased.vcf.gz_size_filtered.vcf. Perhaps "bcftools merge" is what you are looking for?

[2023-08-16 17:30:11,90] [info] WorkflowManagerActor: Workflow actor for b723869b-5486-4002-8528-d607428b4ad7 completed with status 'Failed'. The workflow will be removed from the workflow store.
[2023-08-16 17:30:26,59] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2023-08-16 17:30:26,90] [info] Workflow polling stopped

**Comment by mikolmogorov** [comment]
Sorry, turns out we had an out-of-date version in the r9 branch! It should be fixed now. Thanks for catching this.

**Comment by saraheger** [comment]
Thanks! Workflow finished successfully.
